# permissions for end users to view appconfigurationsources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appconfigurationsource-viewer-role
rules:
- apiGroups:
  - configprovider.azappconfig.io
  resources:
  - appconfigurationsources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configprovider.azappconfig.io
  resources:
  - appconfigurationsources/status
  verbs:
  - get
