# permissions for end users to edit appconfigurationsources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appconfigurationsource-editor-role
rules:
- apiGroups:
  - configprovider.azappconfig.io
  resources:
  - appconfigurationsources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - configprovider.azappconfig.io
  resources:
  - appconfigurationsources/status
  verbs:
  - get
