---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - configprovider.azappconfig.io
  resources:
  - appconfigurationsources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - configprovider.azappconfig.io
  resources:
  - appconfigurationsources/finalizers
  verbs:
  - update
- apiGroups:
  - configprovider.azappconfig.io
  resources:
  - appconfigurationsources/status
  verbs:
  - get
  - patch
  - update
